spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/games_membership?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations:
      data-locations: classpath:dml.sql

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com:
      tutorial:
        spring-boot: DEBUG

  thymeleaf:
    cache: false

  file:
    path: logs

webhook:
  slack:
    url: